# Generated by Django 3.0.7 on 2021-05-07 11:00

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tenderapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_sale', models.BooleanField(default=False)),
                ('is_finance', models.BooleanField(default=False)),
                ('is_purchase', models.BooleanField(default=False)),
                ('is_management', models.BooleanField(default=False)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Budget_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_no', models.IntegerField(default=0)),
                ('rml_no', models.IntegerField(default=0)),
                ('allocate', models.IntegerField(default=0)),
                ('utilized', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
                ('attachment', models.FileField(blank=True, default='', null=True, upload_to='budget/', verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('remain_amount', models.IntegerField(default=0)),
                ('transaction_type', models.CharField(default='', max_length=200)),
                ('transaction_mode', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(default='2021-05-01')),
                ('transaction_id', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('mobile', models.IntegerField(default=0, validators=[tenderapp.models.phoneValidation])),
                ('email', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=200)),
                ('is_gst', models.BooleanField(blank=True, default=False, null=True)),
                ('gstin', models.CharField(default='', max_length=100)),
                ('bank_name', models.CharField(default='', max_length=100)),
                ('pan', models.CharField(default='', max_length=100)),
                ('ifsc', models.CharField(default='', max_length=100)),
                ('account_no', models.IntegerField(default=0)),
                ('is_pan', models.BooleanField(blank=True, default=False, null=True)),
                ('black_list', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_id', models.IntegerField(default=0)),
                ('invoice_id', models.IntegerField(default=0)),
                ('vendor', models.CharField(default='', max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('payment_terms', models.CharField(default='', max_length=200)),
                ('due_date', models.DateTimeField(default='2021-05-01')),
                ('payment_type', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(default='2021-05-01')),
                ('request_by', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('project_no', models.IntegerField(default=0)),
                ('tds', models.IntegerField(default=0)),
                ('tds_type', models.CharField(default='', max_length=100)),
                ('adv_pay', models.IntegerField(default=0)),
                ('net_pay_amt', models.IntegerField(default=0)),
                ('bal_pay_amt', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_for', models.CharField(default='', max_length=255)),
                ('rml', models.IntegerField(default=0)),
                ('sub_total', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('total_gst', models.IntegerField(default=0)),
                ('total_sgst', models.IntegerField(default=0)),
                ('total_cgst', models.IntegerField(default=0)),
                ('attachment', models.FileField(blank=True, default='', null=True, upload_to='files/', verbose_name='')),
                ('po_date', models.DateTimeField(default=datetime.datetime(2021, 5, 7, 16, 30, 16, 863028))),
                ('total_igst', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='tenderapp.Budget_model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenderapp.Vendor_Model')),
            ],
            options={
                'db_table': 'Purchase_Order_Model',
            },
        ),
        migrations.CreateModel(
            name='Particulars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.CharField(default='', max_length=100)),
                ('tax_value', models.IntegerField(default=0)),
                ('gst', models.IntegerField(default=0)),
                ('cgst', models.IntegerField(default=0)),
                ('sgst', models.IntegerField(default=0)),
                ('igst', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='tenderapp.Purchase_Order_Model')),
            ],
            options={
                'db_table': 'Particulars',
            },
        ),
        migrations.CreateModel(
            name='Invoice_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_for', models.CharField(default='', max_length=255)),
                ('rml', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('total_igst', models.IntegerField(default=0)),
                ('total_sgst', models.IntegerField(default=0)),
                ('total_cgst', models.IntegerField(default=0)),
                ('grand_total', models.IntegerField(default=0)),
                ('remark', models.CharField(default='', max_length=1000)),
                ('terms', models.CharField(default='', max_length=1000)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2021, 5, 7, 16, 30, 16, 865000))),
                ('invoice_date', models.DateTimeField(default=datetime.datetime(2021, 5, 7, 16, 30, 16, 865000))),
                ('total_gst', models.IntegerField(default=0)),
                ('po_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenderapp.Purchase_Order_Model')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenderapp.Budget_model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenderapp.Vendor_Model')),
            ],
            options={
                'db_table': 'Invoice_Model',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('igst', models.IntegerField(default=0)),
                ('cgst', models.IntegerField(default=0)),
                ('sgst', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('gst', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='tenderapp.Invoice_Model')),
            ],
            options={
                'db_table': 'Invoice',
            },
        ),
    ]
