# Generated by Django 3.2 on 2021-05-07 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenderapp', '0002_auto_20210507_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_model',
            name='user',
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 17, 23, 38, 182433)),
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 17, 23, 38, 182433)),
        ),
        migrations.AlterField(
            model_name='purchase_order_model',
            name='po_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 17, 23, 38, 181406)),
        ),
    ]
