# Generated by Django 3.2 on 2021-05-07 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenderapp', '0004_auto_20210507_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget_model',
            name='user',
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 17, 36, 53, 69176)),
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 17, 36, 53, 70176)),
        ),
        migrations.AlterField(
            model_name='purchase_order_model',
            name='po_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 17, 36, 53, 67181)),
        ),
    ]
