from django.urls import path
from.import views

urlpatterns = [
    path("", views.home, name="home"),
    path("view_p/", views.view_p, name="view_p"),
    path("property/", views.property1, name="property"),
    path('excel', views.export_users_xls, name='export_excel'),
    path("purchase_register/", views.purchase_register.as_view(), name="purchase_register"),
    path("management_register/", views.management_register.as_view(), name="management_register"),
    path("sale_register/", views.sale_register.as_view(), name="sale_register"),
    path("finance_register/", views.finance_register.as_view(), name="finance_register"),
    path("purchase_dashboard/", views.purchase_dashboard, name="purchase_dashboard"),
    path("management_dashboard/", views.management_dashboard, name="management_dashboard"),
    path("sale_dashboard/", views.sale_dashboard, name="sale_dashboard"),
    path("finance_dashboard/", views.finance_dashboard, name="finance_dashboard"),
    path("login/", views.login, name="login"),
    # path("logout/", views.log, name="logout"),

    path("new_tender/", views.new_tender, name="new_tender"),
    path("view_tender/", views.view_tender, name="view_tender"),
    path("update_tender_status/", views.update_tender_status, name="update_tender_status"),
    path("request_tender_fee/", views.request_tender_fee, name="request_tender_fee"),
    path("sales_order/", views.sales_order, name="sales_order"),
    path("request_BG/", views.request_BG, name="request_BG"),
    path("prepare_budget/", views.prepare_budget, name="prepare_budget"),
    path("view_budget/", views.view_budget, name="view_budget"),
    path("update_budget/", views.update_budget, name="update_budget"),
    path("request_quotation/", views.request_quotation, name="request_quotation"),
    path("new_vendor/", views.new_vendor, name="new_vendor"),
    path("error_page/", views.error_page, name="error_page"),
    path("purchase_order/", views.purchase_order, name="purchase_order"),
    path("new_invoice/", views.new_invoice, name="new_invoice"),
    path("cash/", views.cash, name="cash"),
    path("tds/", views.tds, name="tds"),
    path("tender_payment/", views.tender_payment, name="tender_payment"),
    path("bg_acknowledge/", views.bg_acknowledge, name="bg_acknowledge"),
    path("bg_issue/", views.bg_issue, name="bg_issue"),
    path("payment_list/", views.payment_list, name="payment_list"),
    path("payment_pending/", views.payment_pending, name="payment_pending"),
    path("pending_payment/", views.pending_payment, name="pending_payment"),
    path("ack_app_payment/", views.ack_app_payment, name="ack_app_payment"),
    path("view_quotation/", views.view_quotation, name="view_quotation"),
    path("received_quotation/", views.received_quotation, name="received_quotation"),
    path("view_purchase_order/", views.view_purchase_order, name="view_purchase_order"),
    path("new_advance_payment/", views.new_advance_payment, name="new_advance_payment"),
    path("view_vendor/", views.view_vendor, name="view_vendor"),
    path("update_vendor/<int:id>/", views.update_vendor, name="update_vendor"),
    path("view_advance_payment/", views.view_advance_payment, name="view_advance_payment"),
    path("view_invoice/", views.view_invoice, name="view_invoice"),
    path("purchase_pending_payment/", views.purchase_pending_payment, name="purchase_pending_payment"),
    path("view_sales_order/", views.view_sales_order, name="view_sales_order"),
    path("view_BG/", views.view_BG, name="view_BG"),
    path("update_BG/", views.update_BG, name="update_BG"),
    path("payment_pay/", views.payment_pay, name="payment_pay"),
    path('delete1/<int:id>/', views.delete1, name='delete1'),
    path("payment_req/", views.payment_req, name="payment_req"),
    path('blacklist/<int:id>/', views.blacklist, name='blacklist'),
    path("view_single_purchase_order/<int:id>/", views.view_single_purchase_order, name="view_single_purchase_order"),
    path('reject/<int:id>/', views.reject, name='reject'),
    path('accept/<int:id>/', views.accept, name='accept'),
    path('view/<int:id>/', views.view, name='view'),
    path('paid_fully/<int:id>/', views.paid_fully, name='paid_fully'),
    path('paid_paritally/<int:id>/', views.paid_paritally, name='paid_paritally'),
    path("view_single_invoice/<int:id>/", views.view_single_invoice, name="view_single_invoice"),
    path('view_single_advance/<int:id>/', views.view_single_advance, name='view_single_advance'),
    path('pay/<int:id>/', views.pay, name='pay'),
    path("new_budget/", views.new_budget, name="new_budget"),
    path("logout/", views.logout_view, name="logout_view"),

    path('process/<int:id>/', views.process, name='process'),
]

